version: '3'

services:
  php:
      build: .
      volumes:
          - .:/var/www/html
      ports:
          - 8080:80
      container_name: php8.2-apache

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: 'mysql'
    ports:
      - "3001:80"

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
