version: '3'

services:
  php:
      build: .
      volumes:
          - .:/var/www/html
      ports:
          - 8080:80
      container_name: php7.2-apache

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: 'mysql'
    ports:
      - "3001:80"

  mysql:
    image: mysql:5.7.44
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    container_name: mysql
    volumes:
      - ./sql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/db:/var/lib/mysql

volumes:
  data-volume:
